spring:
  datasource:
    url: jdbc:sqlserver://aqibnagarro.database.windows.net:1433;database=aqibdb;user=aqibnagarro@aqibnagarro;password=aqib@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: aqibnagarro
    password: aqib@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
      